<a href="https://colab.research.google.com/github/shreecode19/python/blob/main/assignment_X.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Find the inverse of the following matrices.

In [ ]:
#matrix A is not a square matrix... so inverse is not possible

In [2]:
import numpy as np
B = np.array([[1,2,3],
     [55,66,7],
     [6,7,12]])
inverse_array = np.linalg.inv(B)
print("Inverse array is ")
print(inverse_array)
print()

Inverse array is 
[[-1.41254753  0.00570342  0.34980989]
 [ 1.17490494  0.01140684 -0.30038023]
 [ 0.02091255 -0.0095057   0.08365019]]



In [3]:
import numpy as np

arr = np.array([[1,2,3,8],
     [5,6,7,5],
     [6,7,12,12],
     [11,12,13,20]])
  
inverse_array = np.linalg.inv(arr)

print("Inverse array is ")

print(inverse_array)

print()

Inverse array is 
[[-0.85576923 -0.78205128  0.25        0.38782051]
 [ 0.75        1.         -0.5        -0.25      ]
 [-0.08653846 -0.06410256  0.25       -0.09935897]
 [ 0.07692308 -0.12820513 -0.          0.05128205]]



2. Find the values of x1, x2 and x3
5x1 + 4 x2 + 3 x3 = 5
6x1 - 8x2   + 7x3 = 15
X1   - x2     +10x3 = 25      


In [4]:
import numpy as np

A = np.array([[5, 4, 3],
              [6, -8, 7],
              [1, -1, 10]])

b = np.array([5, 15, 25])

x = np.linalg.solve(A, b)

print(x)

[-0.50788091 -0.0262697   2.54816112]


3.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [5]:
import numpy as np

array=np.zeros(10)

print("An array of 10 zeros:")

print(array)

array=np.ones(10)

print("An array of 10 ones:")

print(array)

array=np.ones(10)*5

print("An array of 10 fives:")

print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


4. Write a NumPy program to compute the eigenvalues and eigenvectors of a given square array.

 B = [[1,2,3],
     [55,66,7],
     [6,7,12]]

In [6]:
import numpy as np

m = np.mat("1 2 3;55 66 7;6 7 12")

print("B:")

print("\n", m)

w, v = np.linalg.eig(m) 

print( "Eigenvalues of the matrix",w)

print( "Eigenvectors of the matrix",v)

B:

 [[ 1  2  3]
 [55 66  7]
 [ 6  7 12]]
Eigenvalues of the matrix [68.81905127 -0.70229368 10.88324241]
Eigenvectors of the matrix [[ 0.03480353  0.77221412  0.21267997]
 [ 0.99144253 -0.6351919  -0.32907749]
 [ 0.12581905 -0.01471714  0.92004089]]


5. Write a NumPy program to generate five random numbers from the normal distribution.

In [7]:
import numpy as np

x = np.random.normal(size=5)

print(x)

[-0.21567736  1.2811615   2.09388079  0.46443146 -0.70724901]


6. Write a NumPy program to generate six random integers between 10 and 30.


In [8]:
import numpy as np

x = np.random.randint(low=10, high=30, size=6)

print(x)

[17 12 17 16 20 13]


7. Write a NumPy program to create a 3x3x3 array with random values.

In [9]:
import numpy as np

x = np.random.random((3,3,3))

print(x)

[[[3.39821489e-01 9.29138512e-01 2.25219155e-01]
  [4.54109244e-01 4.55877827e-01 5.20454073e-01]
  [3.85198901e-01 4.76849298e-01 3.17769981e-01]]

 [[7.28185203e-01 1.60536770e-01 1.44600462e-01]
  [7.78200366e-01 1.67837085e-01 6.82512591e-01]
  [4.54240408e-01 9.79116245e-02 3.64824731e-02]]

 [[7.86358755e-02 4.31579227e-01 1.69854022e-04]
  [3.23373984e-01 4.69908868e-01 6.46687032e-01]
  [9.08755515e-01 1.86447083e-01 4.13289444e-01]]]


8. `Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [10]:
import numpy as np

x = np.random.random((5,5))

print("Array:")

print(x) 

xmin, xmax = x.min(), x.max()

print("Minimum and Maximum Values:")

print(xmin, xmax)

Array:
[[0.63106055 0.87682009 0.41378136 0.8778041  0.17717488]
 [0.462186   0.96428649 0.52684014 0.64503829 0.95647916]
 [0.23772475 0.73828439 0.42683057 0.92163842 0.56928993]
 [0.21296402 0.49556653 0.20781847 0.86534934 0.60370398]
 [0.35017074 0.41423278 0.20441772 0.7949751  0.17133526]]
Minimum and Maximum Values:
0.17133525997738275 0.9642864860532224


9. Write a NumPy program to normalize a 3x3 random matrix.

In [11]:
import numpy as np

x= np.random.random((3,3))

print("matrix:")

print(x)

xmax, xmin = x.max(), x.min()

x = (x - xmin)/(xmax - xmin)

print("Normalizing matrix:")

print(x)

matrix:
[[0.35430117 0.53703811 0.49356377]
 [0.97832216 0.66308555 0.06423107]
 [0.34135486 0.83979865 0.53954769]]
Normalizing matrix:
[[0.31733172 0.5172428  0.46968262]
 [1.         0.65513655 0.        ]
 [0.30316868 0.84845764 0.51998824]]


10. Write a NumPy program to create a random vector of size 10 and sort it.

In [12]:
import numpy as np

x = np.random.random(10)

print("vector:")

print(x)

x.sort()

print("Sorted vector:")

print(x)

vector:
[0.6108806  0.72827318 0.29723957 0.93598156 0.56626876 0.95437587
 0.83974083 0.41256825 0.83595112 0.4663451 ]
Sorted vector:
[0.29723957 0.41256825 0.4663451  0.56626876 0.6108806  0.72827318
 0.83595112 0.83974083 0.93598156 0.95437587]


11. Write a NumPy program to check if two random arrays are equal or not.

In [27]:
import numpy as np

x = np.random.randint(0,2,6)

print("1st array:")

print(x)

y = np.random.randint(0,2,6)

print("2nd array:")

print(y)

print("Test above two arrays are equal or not")

array_equal = np.allclose(x, y)

print(array_equal)

1st array:
[0 0 1 1 0 1]
2nd array:
[1 0 1 1 1 0]
Test above two arrays are equal or not
False


12. Write a NumPy program to create a random vector of size 15 and replace the maximum value by -1.

In [26]:
import numpy as np
x = np.random.random(15)
print("Vector:")
print(x)
x[x.argmax()] = -1
print("Replacing max value by -1:")
print(x)

Vector:
[0.80640973 0.0138268  0.74005531 0.28136718 0.70145332 0.56205563
 0.36213703 0.23137079 0.05654066 0.82768679 0.32393345 0.8329959
 0.0902187  0.69033957 0.73926029]
Replacing max value by -1:
[ 0.80640973  0.0138268   0.74005531  0.28136718  0.70145332  0.56205563
  0.36213703  0.23137079  0.05654066  0.82768679  0.32393345 -1.
  0.0902187   0.69033957  0.73926029]


13. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on a flattened array.
  A = [[1,2]
       [11,12]]

In [25]:
import numpy as np

a = np.array([[1,2],[11,12]])

print("Original array:")

print(a)

print("Sort the array along the first axis:")

print(np.sort(a, axis=0))

print("Sort the array along the last axis:")

print(np.sort(a))

print("Sort the flattened array:")

print(np.sort(a, axis=None))

Original array:
[[ 1  2]
 [11 12]]
Sort the array along the first axis:
[[ 1  2]
 [11 12]]
Sort the array along the last axis:
[[ 1  2]
 [11 12]]
Sort the flattened array:
[ 1  2 11 12]


14. Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describe the sort order by multiple columns and the sorted data.

id   123 126 140 152
height 145 155 165 153  

In [24]:
import numpy as np

student_id = np.array([123, 126, 140, 152])

student_height = np.array([145, 155, 165, 153])

indices = np.lexsort((student_id, student_height))

print("Sorted indices:")

print(indices)

print("Sorted data:")

for n in indices:
  
  print(student_id[n], student_height[n])

Sorted indices:
[0 3 1 2]
Sorted data:
123 145
152 153
126 155
140 165


15. Write a NumPy program to get the indices of the sorted elements of a given array.
X = [1023 5202 6230 1671 1682 5241 4532]

In [23]:
import numpy as np

student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

print("array:")

print(student_id)

i = np.argsort(student_id)

print("Indices of the sorted elements of a given array:")

print(i)

array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


16. Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.
Y = [(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]

In [22]:
import numpy as np

complex_num = [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]

print("array:")

print(complex_num)

print("\nSorting given complex no.")

print(np.sort_complex(complex_num))


array:
[(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]

Sorting given complex no.
[1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]


17. Multiply AXB
A = [[1,2],
     [11,12],
     [12,15]]
B = [[1,2,3],
     [11,12,13]]

In [21]:
import numpy as np

mat1 = ([1, 2],[11 ,12],[12, 15])

mat2 = ([1, 2, 3],[11, 12, 13])
  
res = np.dot(mat1,mat2)

print(res)

[[ 23  26  29]
 [143 166 189]
 [177 204 231]]


18. Write a NumPy program to compute ex, element-wise of a given array.
 A = [1,5,6,9]

In [20]:
import numpy as np

x = np.array([1, 5, 6, 9], np.int32)

print("array: ")

print(x)

print("\ne^x, element-wise:")

r = np.exp(x)

print(r)

array: 
[1 5 6 9]

e^x, element-wise:
[2.71828183e+00 1.48413159e+02 4.03428793e+02 8.10308393e+03]


19. Write a NumPy program to compute natural, base 10, and base 2 logarithms for all elements in a given array.
A = [1,2.5,56,19]


In [19]:
import numpy as np

x = np.array([1, 2.5, 56, 19])

print("array: ")

print(x)

print("\nNatural log =", np.log(x))

print("Common log =", np.log10(x))

print("Base 2 log =", np.log2(x))

array: 
[ 1.   2.5 56.  19. ]

Natural log = [0.         0.91629073 4.02535169 2.94443898]
Common log = [0.         0.39794001 1.74818803 1.2787536 ]
Base 2 log = [0.         1.32192809 5.80735492 4.24792751]


20. Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.
 A = [[ 0 1 2 3 4 5]
 [ 6 7 8 9 10 11]]

In [18]:
import numpy as np

x = np.arange(12).reshape((2, 6))

print("array:")

print(x)

r1 = np.ptp(x, 1)

r2 = np.amax(x, 1) - np.amin(x, 1)

assert np.allclose(r1, r2)

print("\nThe Difference is:")

print(r1)

array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

The Difference is:
[5 5]


21. Write a NumPy program to compute the median of a flattened given array.
 B =[[ 0 1 2 3 4 5]
 [ 6 7 8 9 10 11]]


In [17]:
import numpy as np

x = np.arange(12).r
eshape((2, 6))
print("Array:")

print(x)

r1 =  np.median(x)

print("\nMedian of array: ")

print(r1)

AttributeError: ignored

22. Write a NumPy program to compute cross-correlation of two given arrays.

 A = [0 1 3]
 B = [2 4 5]


In [16]:
import numpy as np

x = np.array([0, 1, 3])

y = np.array([2, 4, 5])

print("Array1:")

print(x)

print("Array2:")

print(y)

print("\nCross-correlation of arrays:\n",np.cov(x, y))


Array1:
[0 1 3]
Array2:
[2 4 5]

Cross-correlation of arrays:
 [[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


23. Write a Python program to count the number of occurrences of each value in a given array of non-negative integers.

A = [0, 1, 6, 1, 4, 1, 2, 2, 7]

In [15]:
import numpy as np

Array = [0, 1, 6, 1, 4, 1, 2, 2, 7] 

print("array:")

print(Array)

print("Number of occurrences of each value in given array: ")

print(np.bincount(Array))

array:
[0, 1, 6, 1, 4, 1, 2, 2, 7]
Number of occurrences of each value in given array: 
[1 3 2 0 1 0 1 1]


24. Write a NumPy program to display all the dates for the month of May, 2021.

In [14]:
import numpy as np

print("May, 2021")

print(np.arange('2021-05', '2021-06', dtype='datetime64[D]'))

May, 2021
['2021-05-01' '2021-05-02' '2021-05-03' '2021-05-04' '2021-05-05'
 '2021-05-06' '2021-05-07' '2021-05-08' '2021-05-09' '2021-05-10'
 '2021-05-11' '2021-05-12' '2021-05-13' '2021-05-14' '2021-05-15'
 '2021-05-16' '2021-05-17' '2021-05-18' '2021-05-19' '2021-05-20'
 '2021-05-21' '2021-05-22' '2021-05-23' '2021-05-24' '2021-05-25'
 '2021-05-26' '2021-05-27' '2021-05-28' '2021-05-29' '2021-05-30'
 '2021-05-31']


25. Write a NumPy program to concatenate element-wise two arrays of string.
 A = ['Python' 'PHP']
B = [' Java' ' C++']


In [13]:
import numpy as np

x1 = np.array(['Python', 'PHP'], dtype=np.str)

x2 = np.array([' Java', ' C++'], dtype=np.str)

print("Array1:")

print(x1)

print("Array2:")

print(x2)

new_array = np.char.add(x1, x2)

print("new array:")

print(new_array)

Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']
new array:
['Python Java' 'PHP C++']
